### ISSUE TITLE
can use it in without full screen?

### ISSUE THREAD

**Issue by red-co** [sethfair/logseq-focus-mode#10]
Can hide them without being full screen? Because the title bar of logoseq occupies too much space, and the color is also very conspicuous,
![image](https://user-images.githubusercontent.com/75922982/162213176-c917b255-527f-4016-9a06-298a550e7402.png)
Thank you very much for making this plugin,

**Comment by sethfair** [comment]
@red-co thanks for the feature request.  Unfortunately, this issue is on Logseq side.  They would need to provide this as an option when creating a window to hide the title bar.  Please post a feature request https://discuss.logseq.com/c/feature-requests/7
