### ISSUE TITLE
Use native Plugin Settings instead of custom menu

### ISSUE THREAD

**Issue by MrEbbinghaus** [sethfair/logseq-focus-mode#12]
Logseq allows for custom [Plugin Settings](https://logseq.github.io/plugins/modules.html#SettingSchemaDesc) in the Settings Menu:
![image](https://user-images.githubusercontent.com/2965273/164983636-d0c1ff70-09ad-445c-b9c0-2ac3a4b0cf7d.png)

focus mode shouldn't introduce an own settings menu, as it adds clutter to the UI and leads to an inconsistent UX.

**Comment by sethfair** [comment]
Thanks for bringing this to my attention.

**Comment by sethfair** [comment]
@MrEbbinghaus which version are you using? I am not seeing the plugin settings in the latest nightly build of Logseq.

**Comment by sethfair** [comment]
![image](https://user-images.githubusercontent.com/3271366/165022732-d9b4d26d-ebc4-46be-bc7a-d0a681e35438.png)

**Comment by MrEbbinghaus** [comment]
I am on Version 0.6.6

Maybe it only appears, if you have at least one plugin that defines custom settings?

Here is an example of custom settings in the writegood plugin
https://github.com/hkgnp/logseq-writegood-plugin/blob/master/src/callSettings.ts

![image](https://user-images.githubusercontent.com/2965273/165050339-c6d58bd7-4bc4-461b-ba2d-a9fa59a8d3be.png)

**Comment by MrEbbinghaus** [comment]
Yes, the settings are only displayed under certain circumstances. 
https://github.com/logseq/logseq/blob/master/src/main/frontend/components/settings.cljs#L654

**Comment by sethfair** [comment]
@MrEbbinghaus the latest version v1.0 now has this.  Let me know how it works for you.
