### ISSUE TITLE
Bug Report: When close the toggle fullscreen mode, Logseq always open fullscreen after restart.

### ISSUE THREAD

**Issue by mzwlevi** [sethfair/logseq-focus-mode#16]
v0.7.6
![Screen Shot 2022-07-07 at 20 13 05](https://user-images.githubusercontent.com/78029539/177770426-20bdbd58-2d19-4849-baf4-6fa60f5642fa.png)

**Comment by sethfair** [comment]
Ok, I have fixed this in v1.0.3.  Thanks for reporting and let me know if its still an issue.

**Comment by mzwlevi** [comment]
> Ok, I have fixed this in v1.0.3. Thanks for reporting and let me know if its still an issue.

Thank you for work.
