### ISSUE TITLE
Modifier Key Shortcuts

### ISSUE THREAD

**Issue by AhmedThahir** [sethfair/logseq-focus-mode#5]
Is there a way to add shortcuts like `ctrl-p` ?
Currently, it's only possible to create letter combination shortcuts.

**Comment by sethfair** [comment]
@AhmedThahir hi, I will take a look.  Thanks for your submission.

**Comment by bmsdubai** [comment]
Also, I request shortcuts for each property.
I would love to implement this on my own, but I don't know how to work with JavaScript at this level.

**Comment by sethfair** [comment]
Hi, the latest version now allows you to set hotkeys with ctrl.  Please note settings have moved to under Settings -> Plugin Settings -> Focus Mode
