### ISSUE TITLE
Add option to hide logseq tabs

### ISSUE THREAD

**Issue by alizehctl** [sethfair/logseq-focus-mode#8]
I love using this plugin to reduce clutter while writing in logseq. However, I often use the logseq-tabs plugin too, which results in some clutter even when focus mode is enabled.

![image](https://user-images.githubusercontent.com/31581044/159007721-049dad01-0277-423b-bd0b-a24872c29c2a.png)

It would be great if there was an option to toggle the visibility of these tabs too.

**Comment by alizehctl** [comment]
Currently, I'm resorting to manually hiding these tabs through the inspector. 

![image](https://user-images.githubusercontent.com/31581044/159008413-4b05e8b1-322d-4e6b-9038-3557aab74341.png)




Here's how that looks

![image](https://user-images.githubusercontent.com/31581044/159008219-ce20c74c-b947-45cc-8d50-20340eeb4f32.png)

**Comment by sethfair** [comment]
@aadilayub thank you for the feature request.  I will take a look at this.

**Comment by sethfair** [comment]
@aadilayub this is now possible with the new version of the focus plugin.  Please update and give it a try.  I used `#logseq-tabs_lsp_main`
![image](https://user-images.githubusercontent.com/3271366/177615819-79610c9c-427b-403f-b000-f62b8910f3da.png)
