### ISSUE TITLE
Hide help button

### ISSUE THREAD

**Issue by Tamriel** [sethfair/logseq-focus-mode#9]
When hiding the right toolbar, a help button appears in the bottom right corner.
This plugin should hide that distracting button.

**Comment by sethfair** [comment]
Hi @Tamriel , thank you for the feature request.  I will add this in the next release.

**Comment by sethfair** [comment]
@Tamriel this is now included in the latest version v1.0.  Please update your plugin and give it a try.  Also note that the settings have been moved to Logseq Settings page.
